### ISSUE TITLE
[Linux] Crashes with segmentation fault when 'xterm' is missing

### ISSUE THREAD

**Issue by v-evets** [rimpy-custom/RimPy#10]
Any action that triggers a download via steamcmd (i.e. install or update) crashes RimPy.
As mentioned [elsewhere](https://github.com/rimpy-custom/RimPy/issues/1), RimPy does not detect steamcmd installed system-wide and in $PATH, so steamcmd was installed via the prompts in RimPy, to the RimPy install directory.

STDOUT from run, selected a random mod in the "downloader" panel, hit download:
`/RimPy.sh`
`ERROR: ld.so: object '$LD_PRELOAD' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.`
`QXcbIntegration: Cannot create platform OpenGL context, neither GLX nor EGL are enabled`
`Qt WebEngine resources not found at //resources. Trying parent directory...`
`Qt WebEngine resources not found at /. Trying application directory...`
`Installed Qt WebEngine locales directory not found at location /translations/qtwebengine_locales. Trying application directory...`
`ERROR: ld.so: object '$LD_PRELOAD' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.`
`ERROR: ld.so: object '$LD_PRELOAD' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.`
`Qt WebEngine resources not found at //resources. Trying parent directory...`
`Qt WebEngine resources not found at /. Trying application directory...`
`Installed Qt WebEngine locales directory not found at location /translations/qtwebengine_locales. Trying application directory...`
`Qt WebEngine resources not found at //resources. Trying parent directory...`
`Qt WebEngine resources not found at /. Trying application directory...`
`Installed Qt WebEngine locales directory not found at location /translations/qtwebengine_locales. Trying application directory...`
`ERROR: ld.so: object '$LD_PRELOAD' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.`
`Qt WebEngine resources not found at //resources. Trying parent directory...`
`Qt WebEngine resources not found at /. Trying application directory...`
`Installed Qt WebEngine locales directory not found at location /translations/qtwebengine_locales. Trying application directory...`
`0.28490454600250814`
`js: Uncaught ReferenceError: qt is not defined`
`js: Failed to normalize error stack: TypeError: Cannot read property 'stack' of null`
`js: Uncaught TypeError: Cannot read property 'lastChild' of undefined`
`js: Failed to normalize error stack: TypeError: Cannot read property 'stack' of null`
`js: Uncaught TypeError: Cannot read property 'parentElement' of null`
`js: Failed to normalize error stack: TypeError: Cannot read property 'stack' of null`
`js: Uncaught TypeError: Cannot read property 'BIsDirty' of undefined`
`js: Uncaught TypeError: Cannot read property 'visible' of null`
`js: Uncaught ReferenceError: qt is not defined`
`js: Uncaught TypeError: Cannot read property 'lastChild' of undefined`
`js: Uncaught TypeError: Cannot read property 'parentElement' of null`
`js: Failed to normalize error stack: TypeError: Cannot read property 'stack' of null`
`js: Failed to normalize error stack: TypeError: Cannot read property 'stack' of null`
`js: Uncaught TypeError: Cannot read property 'lastChild' of undefined`
`https://steamcommunity.com/sharedfiles/filedetails/?id=2202185773&searchtext=`
`QCoreApplication::exec: The event loop is already running`
`./RimPy.sh: line 2:  9542 Segmentation fault      LD_PRELOAD='libpcre.so.3:$LD_PRELOAD' ./RimPy`

Ed. Found the logs, so here's one of those:
`INFO:root:RimPy start of initialization`
`INFO:root:UI generated`
`INFO:root:Rimworld object instantiation`
`INFO:root:Mod initialized: Heat Map (falconne.heatmap)`
`INFO:root:Mod initialized: HugsLib (unlimitedhugs.hugslib)`
`INFO:root:Mod initialized: Prepare Landing (neitsa.preparelanding)`
`INFO:root:Mod initialized: Harmony (brrainz.harmony)`
`INFO:root:Mod initialized: Pick Up And Haul (mehni.pickupandhaul)`
`INFO:root:Mod initialized: Prepare For Combat (bar0th.pfc)`
`INFO:root:Mod initialized: Dubs Mint Menus (dubwise.dubsmintmenus)`
`INFO:root:Mod initialized: RPG Style Inventory Revamped (sandy.rpgstyleinventory.avilmask.revamped)`
`INFO:root:Mod initialized: Numbers (mehni.numbers)`
`INFO:root:Mod initialized: Achtung! (brrainz.achtung)`
`INFO:root:Mod initialized: EdB Prepare Carefully (edb.preparecarefully)`
`INFO:root:Mod initialized: Replace Stuff (uuugggg.replacestuff)`
`INFO:root:Mod initialized: RimHUD (jaxe.rimhud)`
`INFO:root:Mod initialized: Royalty [Official DLC] (ludeon.rimworld.royalty)`
`INFO:root:Mod initialized: Ideology [Official DLC] (ludeon.rimworld.ideology)`
`INFO:root:Mod initialized: Core (ludeon.rimworld)`
`INFO:root:ModsConfig.xml content:`

`brrainz.harmony`
`ludeon.rimworld`
`ludeon.rimworld.royalty`
`ludeon.rimworld.ideology`
`unlimitedhugs.hugslib`
`brrainz.achtung`
`dubwise.dubsmintmenus`
`edb.preparecarefully`
`falconne.heatmap`
`mehni.numbers`
`mehni.pickupandhaul`
`bar0th.pfc`
`neitsa.preparelanding`
`sandy.rpgstyleinventory.avilmask.revamped`
`uuugggg.replacestuff`
`jaxe.rimhud`

`INFO:root:Rimworld object instantiation completed`
`INFO:root:Game version: 1.3.3117 rev660`
`INFO:root:Game folder: /home/steve/Games/RimWorld/game`
`INFO:root:Configs folder: /home/steve/.config/unity3d/Ludeon Studios/RimWorld by Ludeon Studios/Config`
`INFO:root:Steam mods folder: `
`INFO:root:Local mods folder: /home/steve/Games/RimWorld/game/Mods`
`INFO:root:RimPy Mod Manager v. 1.1.3.17`
`INFO:root:Populating mods`
`INFO:root:Game version: 1.3.3117 rev660`
`INFO:root:Game folder: /home/steve/Games/RimWorld/game`
`INFO:root:Configs folder: /home/steve/.config/unity3d/Ludeon Studios/RimWorld by Ludeon Studios/Config`
`INFO:root:Steam mods folder: `
`INFO:root:Local mods folder: /home/steve/Games/RimWorld/game/Mods`
`INFO:root:Mods added to QTreeWidgets`
`INFO:root:Populating mods`
`INFO:root:Mod initialized: Heat Map (falconne.heatmap)`
`INFO:root:Mod initialized: HugsLib (unlimitedhugs.hugslib)`
`INFO:root:Mod initialized: Prepare Landing (neitsa.preparelanding)`
`INFO:root:Mod initialized: Harmony (brrainz.harmony)`
`INFO:root:Mod initialized: Pick Up And Haul (mehni.pickupandhaul)`
`INFO:root:Mod initialized: Prepare For Combat (bar0th.pfc)`
`INFO:root:Mod initialized: Dubs Mint Menus (dubwise.dubsmintmenus)`
`INFO:root:Mod initialized: RPG Style Inventory Revamped (sandy.rpgstyleinventory.avilmask.revamped)`
`INFO:root:Mod initialized: Numbers (mehni.numbers)`
`INFO:root:Mod initialized: Achtung! (brrainz.achtung)`
`INFO:root:Mod initialized: EdB Prepare Carefully (edb.preparecarefully)`
`INFO:root:Mod initialized: Replace Stuff (uuugggg.replacestuff)`
`INFO:root:Mod initialized: RimHUD (jaxe.rimhud)`
`INFO:root:Mod initialized: Royalty [Official DLC] (ludeon.rimworld.royalty)`
`INFO:root:Mod initialized: Ideology [Official DLC] (ludeon.rimworld.ideology)`
`INFO:root:Mod initialized: Core (ludeon.rimworld)`
`INFO:root:ModsConfig.xml content:`

`brrainz.harmony`
`ludeon.rimworld`
`ludeon.rimworld.royalty`
`ludeon.rimworld.ideology`
`unlimitedhugs.hugslib`
`brrainz.achtung`
`dubwise.dubsmintmenus`
`edb.preparecarefully`
`falconne.heatmap`
`mehni.numbers`
`mehni.pickupandhaul`
`bar0th.pfc`
`neitsa.preparelanding`
`sandy.rpgstyleinventory.avilmask.revamped`
`uuugggg.replacestuff`
`jaxe.rimhud`

`INFO:root:Game version: 1.3.3117 rev660`
`INFO:root:Game folder: /home/steve/Games/RimWorld/game`
`INFO:root:Configs folder: /home/steve/.config/unity3d/Ludeon Studios/RimWorld by Ludeon Studios/Config`
`INFO:root:Steam mods folder: `
`INFO:root:Local mods folder: /home/steve/Games/RimWorld/game/Mods`
`INFO:root:Mods added to QTreeWidgets`
`CRITICAL:root:Exception`
`Traceback (most recent call last):`
`  File "/home/steve/Games/RimPy_Linux~/rimpy.py", line 5177, in steamDownload`
`  File "/home/steve/Games/RimPy_Linux~/rimpy.py", line 3539, in tryToOpen`
`  File "/home/steve/Games/RimPy_Linux~/subprocess.py", line 951, in __init__`
`  File "/home/steve/Games/RimPy_Linux~/subprocess.py", line 1823, in _execute_child`
`FileNotFoundError: [Errno 2] No such file or directory: 'xterm'`

I see RimPy just crashes and burns if external binaries aren't available, rather than producing useful errors...

Could we perhaps, uhh, use the users preferred terminal emulator rather than hardcoding a silent, crash-inducing dependency on an application from the 1970s? We have xdg-terminal for stuff like this.
I'm kinda baffled as to why FileNotFound on an external tool is ending up at a critical root exception anyways, but that's another matter.

OS: Gentoo GNU/Linux (2.6 "stable" amd64)
RimPy release: 1.1.3.17 (appears to be the latest with a GNU/Linux build)

**Comment by rimpy-custom** [comment]
RimPy need xterm to handle downloading process

**Comment by v-evets** [comment]
So it seems, I found this out the hard way as it doesn't appear to be documented... Candidate for the "RimPy crashes" section of the FAQ?

It's also kinda ugly to segfault there instead of informing the user about the problem as TBH. If I'd got a warning rather than a hard crash, I would have just installed xterm, rather than creating an issue.

**Comment by rimpy-custom** [comment]
@ForeverZer0 I have got this list:
("x-terminal-emulator", "urxvt", "rxvt", "terminator", "Eterm", "aterm", "xterm", "gnome-terminal", "roxterm", "xfce4-terminal")
Do I missing smth in it?

**Comment by rimpy-custom** [comment]
Should be fixed in next release

**Comment by ForeverZer0** [comment]
I would personally add `konsole` as it is the common/default for many KDE-based desktop environments, but it probably isn't possible to ever come up with any "complete" list, as there are so many. The best you can probably do is take the few most common desktop environments and distros, and include what they use as a default. Maybe even just use a Slant article for "most popular terminal emulators" or something as a quick list to build from. As this is is somewhat of a fallback solution, I wouldn't labor myself too much trying to be complete, the most common should be sufficient.
