### ISSUE TITLE
`NSSUTIL_3.82' not found

### ISSUE THREAD

**Issue by CSergienko** [rimpy-custom/RimPy#100]
RimPy no longer working after upgrading to Ubuntu 22.10. This is the stack trace:

```
$ ./RimPy
Traceback (most recent call last):
  File "/home/myuser/bin/RimPy/rimpy.py", line 26, in <module>
ImportError: /home/myuser/bin/RimPy/PyQt5/../libnssutil3.so: version `NSSUTIL_3.82' not found (required by /lib/x86_64-linux-gnu/libnss3.so)
```

**Comment by TBleader** [comment]
https://github.com/rimpy-custom/RimPy/issues/92#issuecomment-1287486116

> Deleting libnssutil3.so from the rimpy folder works for me. Seems to be a version conflict between the locally installed version of libnss and the packaged libnss-util.

Try this, it might work

**Comment by rimpy-custom** [comment]
Try latest prerelease. Closing for now since issue was already reported in #92
