### ISSUE TITLE
[Linux] [Gentoo] [1.2.6.28] All download jobs report "Ошибка открытия URL:"

### ISSUE THREAD

**Issue by v-evets** [rimpy-custom/RimPy#101]
Latest 1.2.6.28 prerelease (due to libnss problems, as with Arch), RimPy launches fine but any native network job fails with the above error.
By "native", I am referring to network jobs run within RimPy itself, not steamcmd or qtwebengine.
e.e. mod browsing and downloads work, but update checks (both rimpy and mods) and automatic download of steamcmd do not.

`Sandboxing disabled by user.`
`Ошибка открытия URL: https://api.github.com/repos/rimpy-custom/RimPy/releases`
`Ошибка открытия URL: https://content-system.gog.com/products/1094900565/os/windows/builds?generation=2`
`Ошибка открытия URL: https://rimworldwiki.com/wiki/Version/Current_version`
`0.8538606709917076`
`js: Uncaught ReferenceError: qt is not defined`
`js: Failed to report error: ReportError() was called without an error to report.`
`js: Uncaught TypeError: Cannot read property 'lastChild' of undefined`
`js: Failed to report error: ReportError() was called without an error to report.`
`js: Uncaught TypeError: Cannot read property 'parentElement' of null`

Additionally, the mod update check appears to retry version checks indefinitely, spamming the console with the above until RimPy is forcibly closed. These entries appear far too fast for an actual lookup and connection attempt to have occured, so I doubt it's a connectivity problem in general.

RimPy 1.2.4.21 (last stable GNU/Linux release) works perfectly here, though it lacks the fixes for RimWorld 1.4.x. No network problems.
This smells like ongoing libnss (probably linking / versioning) issues to me. 
As others have already suggested, if you released source we could likely fix this fairly easily by linking against system libraries.

Ed. probably just another #72 

For now I'm using 1.2.4.21 for updates and 1.2.6.28 for sorting and everything else. Workable, but annoying.
This has been a problem for quite some time now, and it makes rimpy considerably less useful than it could be.

**Comment by rimpy-custom** [comment]
Closing for now. Reopen if issue wasn't fixed with latest Linux build 1.2.6.28.

**Comment by v-evets** [comment]
Nope, exactly the same behaviour with the latest (1 hr old) 1.2.6.28 tarball.

Please re-open, as I have no privs to do so.

Ed. My earlier speculation was incorrect. I have captured and decrypted RimPy's network traffic, and it is in fact making several successful connections (e.g. the steam game version check at https://steamcommunity.com/app/294100/workshop/.)
The addresses that STDOUT reports as "Ошибка открытия" are not in the capture at all.

So networking isn't broken generally, but many operations are reporting "not found" (or similar), seemingly without even trying.
These are broken:
* RimPy version check https://api.github.com/repos/rimpy-custom/RimPy/releases
* GOG game version check (https://content-system.gog.com/products/1094900565/os/windows/builds)
* Rimworld wiki version check (https://rimworldwiki.com/wiki/Version/Current_version)
* All mod update checks (e.g. https://steamcommunity.com/sharedfiles/filedetails/?id=1423699208)

None of them generate a single packet, in fact I'm not even seeing applicable DNS lookups.

Again, this would be much easier to debug if I had access to the source code... Source code that you are almost certainly violating the GNU GPL by not providing, by the way.
