### ISSUE TITLE
Please reopen #72, and/or #101

### ISSUE THREAD

**Issue by v-evets** [rimpy-custom/RimPy#106]
#72 and #101 have been closed with "Reopen if issue wasn't fixed with latest Linux build 1.2.6.28.", yet as far as I can tell (correct me if I am wrong here) non-contributors cannot reopen issues closed by the project owner.

Updates on GNU/Linux are still broken, and I have updated #101 with some further investigation.

**Comment by rimpy-custom** [comment]
May you try latest 1.2.6.29?

**Comment by v-evets** [comment]
Scratch that, just got hit by some random caching shenanegans as there's no version in the archive filename.
1.2.6.29 (215.7MiB) works fine. Thanks.

**Comment by rimpy-custom** [comment]
Closed since issue resolved
