### ISSUE TITLE
Request: Add RimPy to the Arch User Repository

### ISSUE THREAD

**Issue by sylvesterroos** [rimpy-custom/RimPy#116]
It would be very handy if RimPy could be installed and kept updated through the AUR

**Comment by jtljac** [comment]
I took a stab at making a package build for Rimpy, you can find my attempt here: [RimPy Pkgbuild.zip](https://github.com/rimpy-custom/RimPy/files/10254072/RimPy.Pkgbuild.zip)
Unfortunately it doesn't quite work correctly as RimPy seems to want write permissions on files in the install directory (The last crash before I gave up was it wanted write permissions on libsteam_api.so)
Feel free to play with my attempt or to fix it and upload it to the aur yourself
