### ISSUE TITLE
Mod incompatibilities

### ISSUE THREAD

**Issue by Crusader2010** [rimpy-custom/RimPy#134]
Hi,

It would be nice to have an option to select and submit mod incompatibilities. Somewhat similar to the sorting rules.
Like, for example, choosing a mod and a list of mods that is incompatible with from your list. Maybe a comment for it too, that can be shown to other users when they have the 2 mods in their list, below/near a generic incompatibility error message.

Thanks

**Comment by rimpy-custom** [comment]
Thx for the idea. But a lot of manual work will be needed to manage the database. Every month there are 1k+ mods released/updated, db manager will need to check incompatibilities for each update. It is a pity but that will not work, db will be bloated with false positives. Let the modders do the job, report incomartibilities to them. Sure some mods are abandoned but we can do nothing about that.
