### ISSUE TITLE
Doing your job & open source 

### ISSUE THREAD

**Issue by cylian914** [rimpy-custom/RimPy#135]
Hey I understand you closed my last issue concerning the code, but 1 you say it was too hated and lock it for no reason, there was literally no hate message, 2 you didn't answer all the questions in #79 . I still don't understand why it's closed source, you don't say any argument why it should be close source and I rly don't understand why it's closed source.

Ps: I'm happy to see you are back in the repo

Have a great day

**Comment by rimpy-custom** [comment]
May I ask you to summarize my point of view from thread #79 ? What was my reasoning in there? Since I have answered your question in it.

**Comment by cylian914** [comment]
You dont want others to touch the code, you prefer having your system then a multiple system fused together m. It's the only argument said

**Comment by rimpy-custom** [comment]
And why do I want that?

**Comment by cylian914** [comment]
Because you don't want to argue with others ?

**Comment by rimpy-custom** [comment]
Sure but why? Because I have in mind how it should work and others that dislike my ideas may fork it and change it in "better way". Cite:
"There always be users that want to change smth "in better way", but sometimes that way is not better. If you go open source, then you have to discuss, prove smth to them. That is
exhausting. I may be wrong on some parts, but for current moment I belive that working on project alone is more efficient in terms of time/results/mental health. But there are several devs that really wanted to help me and share my opinion, I have met them and I feel bad that rejected their help."

Project is alive for several years and is stable because I may control the process and focus on development instead of proving someone that my ideas will work better. That is it. Instead of proving something, I work on making it better.

**Comment by cylian914** [comment]
If the "better way" is the wrong way it will not become popular, people don't change software everyday and without any reason, the better way needs to be way better then actual implementation for starting the shift to this version and if it's that better nothing stop you to implementing it in the current version

Also having it open source doesn't mean you can't control it

**Comment by rimpy-custom** [comment]
A lot of users do not know what is better in long run. And that is why they are prone to make wrong conclusions. I work on this project several years and saw a lot of such situations. That is why I have to disagree with you. I gave you my reasoning.

**Comment by Lippiece** [comment]
@rimpy-custom 
I understand that I'm necroposting, but this reminded me of some repos that argue similarly and simply reject most of the PRs. There's literally nothing you would need to do to deal with "people who know better".

**Comment by 32bitx64bit** [comment]
> A lot of users do not know what is better in long run. And that is why they are prone to make wrong conclusions. I work on this project several years and saw a lot of such situations. That is why I have to disagree with you. I gave you my reasoning.

Talk about arrogant. Your entire reasoning is you don't want others to dare touch the secret sauce. And calling them idiots, and saying they'll just make wrong decisions .

Its a shame you don't support open source development. And I really hope someone who does support open source development, comes around and makes a alternative to this. As it just pains me to use this now that I have found this out.

Its one thing to be proprietary, its another to completely say open source = bad.

**Comment by Lippiece** [comment]
> > A lot of users do not know what is better in long run. And that is why they are prone to make wrong conclusions. I work on this project several years and saw a lot of such situations. That is why I have to disagree with you. I gave you my reasoning.
> 
> Talk about arrogant. Your entire reasoning is you don't want others to dare touch the secret sauce. And calling them idiots, and saying they'll just make wrong decisions .
> 
> Its a shame you don't support open source development. And I really hope someone who does support open source development, comes around and makes a alternative to this. As it just pains me to use this now that I have found this out.
> 
> Its one thing to be proprietary, its another to completely say open source = bad.

You're welcome. This thread should be closed, as this repo, too. https://github.com/RimSort/RimSort
