### ISSUE TITLE
Major license violations

### ISSUE THREAD

**Issue by tazz4843** [rimpy-custom/RimPy#140]
RimPy appears to use a few GPLv3 licensed libraries, and they are all distributed in the .tar.gz file downloaded (at least for Linux). This is a blatant violation of GPLv3, unless RimPy is open source. Unless you have negotiated a commercial license with each and every GPLv3 licensed downstream library you use, this could be a very big problem at some point in the future, with some legal repercussions. The fix to this would be open sourcing it or negotiating a commercial license with each and every one of your GPLv3 dependencies.

**Comment by rimpy-custom** [comment]
Thank you for your propostition. Will check what can be done to fix that.
