### ISSUE TITLE
License violation risks

### ISSUE THREAD

**Issue by Nehctarg** [rimpy-custom/RimPy#147]
## License violation risks 
As already outlined in #140 distributing RimPy in it's current license state is **illegal** and **against GitHub's TOS**. 
Thus closing this issue and ignoring it (like #140) does not help you in any way, as these violations possibly expose you to a trial (should someone go so far as to inform one of the law firms, dealing with this topic) or to a straight up ban from GitHub as they want to avoid being put on trail for providing a platform for your illegal distribution of GPL code.
## How can you avoid these things (mutually exclusive)
- Immediately stop distributing RimPy (remove all releases)
- Remove the GPL code within RimPy
- License RimPy's code under the GPL 
- Assure that you hold a different license agreement with each of the GPL libraries

**Comment by malnormalulo** [comment]
I am not a lawyer and this is not legal advice, but just to offer a little more interpretation:

>- Immediately stop distributing RimPy (remove all releases)
>- Remove the GPL code within RimPy

I'm not sure either of these remedies the situation. The application has already been distributed, and ceasing distribution does not undo any violations which have already occurred.

Releasing the RimPy code under GPL, however, should satisfy the terms of the license (though its lateness may still be an issue). It's worth noting that this is more of an obligation than an option – it is what the developer has already agreed to do, intentionally or not, by using those libraries.
