### ISSUE TITLE
Request for new Linux release

### ISSUE THREAD

**Issue by heatherathebyne** [rimpy-custom/RimPy#22]
May we have another Linux release? I'm really interested in some of the new features. Thank you :)

**Comment by rimpy-custom** [comment]
There are issues I cannot resolve for Linux build. It will be released asap.

**Comment by heatherathebyne** [comment]
Thank you! As an aside, are you interested in publishing the source and accepting contributions from the community? I know you've said the code isn't very clean, but I don't think the community would mind, given the opportunity to work on such a vital application.

**Comment by rimpy-custom** [comment]
Next release will have Linux version
