### ISSUE TITLE
[Linux] Rimworld Fails to Launch from Rimpy

### ISSUE THREAD

**Issue by PaxiTheAlchemist** [rimpy-custom/RimPy#23]
# Rimworld Fails to Launch from Rimpy

## Details

Upon launching Rimworld from within Rimpy (Linux binary [1.1.3.17](https://github.com/rimpy-custom/RimPy/releases/tag/1.1.3.17)) it would seem like Rimworld does launch, evident as my resolution changes as the game goes into fullscreen, however, it quickly reverts the resolution to which nothing else occurs after. Within my terminal, it would seem like Rimpy does recognize the location of the Rimworld executable, however, the described events above occur instead. Here is the terminal output whenever `Run!` is clicked

```
Found path: /home/paxi/.steam/debian-installation/steamapps/common/RimWorld/RimWorldLinux
```

As a note, Rimworld launches fine when using the executable manually or through Steam itself. I am also using No mods, and the directories are properly configured. I will like to say that when I launched Rimpy for the first time, the directories did not automatically configure themselves as seen within Windows or the Linux guide (linked on the Steam Page)

## Additional Info

```
OS: Linux Mint 20.2 x86_64
Arch: x64
Kernel: 5.4.0-90-generic
Graphics: Nvidia
```

**Comment by rimpy-custom** [comment]
Provide more data. Logs, screenshots, video, etc.

**Comment by rimpy-custom** [comment]
New build was released. Reopen the issue if you still get the issue.

**Comment by PaxiTheAlchemist** [comment]
## Terminal Output

```
 paxi@Computer  ~/RimPy_Linux  ./RimPy.sh
Qt WebEngine resources not found at //resources. Trying parent directory...
Qt WebEngine resources not found at /. Trying application directory...
Installed Qt WebEngine locales directory not found at location /translations/qtwebengine_locales. Trying application directory...
Qt WebEngine resources not found at //resources. Trying parent directory...
Qt WebEngine resources not found at /. Trying application directory...
Installed Qt WebEngine locales directory not found at location /translations/qtwebengine_locales. Trying application directory...
Qt WebEngine resources not found at //resources. Trying parent directory...
Qt WebEngine resources not found at /. Trying application directory...
Installed Qt WebEngine locales directory not found at location /translations/qtwebengine_locales. Trying application directory...
Qt WebEngine resources not found at //resources. Trying parent directory...
Qt WebEngine resources not found at /. Trying application directory...
Installed Qt WebEngine locales directory not found at location /translations/qtwebengine_locales. Trying application directory...
2.1991481459999704
js: Uncaught ReferenceError: qt is not defined
js: Failed to report error: ReportError() was called without an error to report.
js: Uncaught TypeError: Cannot read property 'lastChild' of undefined
js: Failed to report error: ReportError() was called without an error to report.
js: Uncaught TypeError: Cannot read property 'parentElement' of null
Found path: /home/paxi/.steam/debian-installation/steamapps/common/RimWorld/RimWorldLinux
```

Here is the log from first launching the bash script from the terminal to clicking the `Run!` button. As a note, only the last line outputs to the console when clicking the `Run!` button. Folder location forms within the application have been filled and the same scenario has been repeated with and without mods/expansions. Here is a screenshot of the application:

## Screenshot

![Rimpy Screenshot](https://imgur.com/AkflKRr.png)

Even with the new release, the same issue still occurs where the application seems to launch as the resolution of my monitor momentarily warps/changes before reverting with Rimworld not launching after

All the information that I have provided within this reply is with using the [1.2.4.21](https://github.com/rimpy-custom/RimPy/releases/tag/1.2.4.21) release, the latest release as of the posting of this reply

**Comment by PaxiTheAlchemist** [comment]
If there is a more verbose debug output that is available to me through the application that you would like to see, please let me know to which ill update this additional information accordingly
