### ISSUE TITLE
macos support

### ISSUE THREAD

**Issue by Daenyth** [rimpy-custom/RimPy#31]
Is there a version with macos support? Or if not, is there source available? The source code tarfile in the releases tab is empty except for the readme

**Comment by rimpy-custom** [comment]
No Mac support, sorry.

**Comment by ELLIOTTCABLE** [comment]
Ditto re: the source-code, I'd be happy to port some of the functionality to macOS.

**Comment by Daenyth** [comment]
@ELLIOTTCABLE if you're still hoping for something, there's an alternate project that supports mac: https://github.com/oceancabbage/RimSort
