### ISSUE TITLE
Stripping mods may strip other content

### ISSUE THREAD

**Issue by Water-Moon** [rimpy-custom/RimPy#32]
The stripping mod function will actually search mods' parent directories, which means it may attempt to remove other files (including your personal files) on the same disk!

![image](https://user-images.githubusercontent.com/43123946/147888877-788e122b-9c64-476e-ba34-bed370de6653.png)
^Look how its attempting to remove several .exes and even the pagefile (the removal of the latter will cause a bsod and unrecoverable damage to other softwares/services utilizing the pagefile)

**Comment by rimpy-custom** [comment]
Should be fixed with new RimPy release. May test that?
