### ISSUE TITLE
Booting RimWorld from RimPy, RimWorld never loads [Linux]

### ISSUE THREAD

**Issue by submeg** [rimpy-custom/RimPy#33]
Hi all,  

Was using RimPy on Windows and it worked fine, but due to lag issues in Windows, I decided to make a dual boot system and play RimWorld in Linux (Ubuntu 20.04.3 LTS 64-bit). 

I am following [this video](https://www.youtube.com/watch?v=xzLCtZTzcz4) on how to use RimPy on Linux.

I have installed RimPy into:  
/home/[USERNAME]/.steam/steam/steamapps/common/RimWorld/Mods

When I navigate to that location via the terminal, I then use the commands:  
`chmod +x ./RimPy`
`./RimPy` 

To run RimPy (trying to create a shortcut to this, but I am new to Linux, so it's more difficult than Windows). When RimPy is loaded, I try and boot RimWorld (with Steam running), but all it does is open a black window (which I presume is RimWorld) which promptly closes.  
  
What am I doing incorrectly? Thanks.

submeg

**Comment by rimpy-custom** [comment]
May test with new RimPy pre-release?

**Comment by rimpy-custom** [comment]
Closing for now. Reopen if issue wasn't fixed with latest Linux build 1.2.6.28.
