### ISSUE TITLE
Upscaling textures crashes computer

### ISSUE THREAD

**Issue by taivo-tobreluts** [rimpy-custom/RimPy#37]
Ticking the "Upscale textures (2x) before conversion" and trying to convert any texture the system reboots (due to GPU crash?).

**Comment by rimpy-custom** [comment]
Might be smth with your computer. Try to stress test your GPU. Close for now. If you do not get issues after stress testing, create new ticket and provide more data - PC specs, RimPy version, Mod list you try to convert.
