### ISSUE TITLE
App opens but I only get a white screen

### ISSUE THREAD

**Issue by ProfessorMinius** [rimpy-custom/RimPy#40]
I've followed all of the guidelines to boot and all I get is a white screen when I open the app. Even after an hour it won't open at all. Here's how it looks
![Untitled](https://user-images.githubusercontent.com/25408719/156461164-6da0f78d-0fa1-49c0-9428-b9c5d7b82d9d.png)
.

**Comment by ProfessorMinius** [comment]
[rimpy.log](https://github.com/rimpy-custom/RimPy/files/8173412/rimpy.log)
This is my last log

**Comment by ProfessorMinius** [comment]
Ok I've managed to crash it and get this message by clicking on random stuff. I've also checked and I have opengl 3.1. How can i fix this?
![image](https://user-images.githubusercontent.com/25408719/156468089-f0b629d5-2e3f-4a2d-8b8e-82eb570a3152.png)

**Comment by rimpy-custom** [comment]
Hi, what is your CPU and GPU?

**Comment by rimpy-custom** [comment]
Closing for now. Feel free to reopn if you still get issues.

**Comment by SameerChaudry** [comment]
I'm a bit late but the problem seems to be related to opengl, I fixed this issue by adding this opengl32.dll file I found on the internet in the rimpy folder. It seems to be safe and it doesn't set off windows defender. I reuploaded it here: https://drive.google.com/file/d/1RgeuQj835igASsex7RRgTDPxkJj-S_dU/view?usp=sharing

**Comment by Hakantasturk** [comment]
> I'm a bit late but the problem seems to be related to opengl, I fixed this issue by adding this random .dll file I found on the internet in the rimpy folder. It seems to be safe and it doesn't set off windows defender. I reuploaded it here: https://drive.google.com/file/d/1RgeuQj835igASsex7RRgTDPxkJj-S_dU/view?usp=sharing

I'm a bit late for reply but thank you so much
