### ISSUE TITLE
[Windows] Attempting to 'share' sorting-rules, *or* drag any mod around in the edit-sorting-rules interface, crashes RimPy to desktop

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [rimpy-custom/RimPy#41]
Title says it all. I'm unable to really do *any* sorting-rule modification without RimPy crashing.

Reliably, clicking 'share' immediately crashes RimPy (no error message or anything of the sort); but also, even attempting to click-and-drag a mod from the left pane into one of the before/after lists *also* crashes RimPy pretty quickly.

(While I'm here: there doesn't appear to be any documentation in the sorting-rules interface? What do I drag where? Why are there two, identical, before/after sections?)

**Comment by ELLIOTTCABLE** [comment]
Okay; upon further investigation - this only happens *if* the "Details" pane is open. I didn't realize you could drag'n'drop without opening the Details pane; and everything appears to work fine if I keep it closed and just use the basic/non-details interface.

**Comment by rimpy-custom** [comment]
Upload crashlogs from RimPy/logs folder, please

**Comment by rimpy-custom** [comment]
May you test with latest pre-release?

**Comment by rimpy-custom** [comment]
Closing for now. Reopen if issue wasn't fixed with latest build 1.2.6.28.
