### ISSUE TITLE
What licence does RimPy use?

### ISSUE THREAD

**Issue by Matyas-Cerny** [rimpy-custom/RimPy#42]
As you do not include a licence with your program and because Qt is licensed under the LGPL and partly GPL, I assume that RimPy uses the GNU GPL or LGPL.
According to [Qt's obligations of the GPL and LGPL](https://www.qt.io/licensing/open-source-lgpl-obligations?hsLang=en) and thusly the obligations of the licenses themselves. You must provide a copy of the licence you're using and in the case of the GNU general public licence you must also provide the source code of you application. Because your application does not show any licences whatsoever, it means that your application cannot be legally distributed. So in this roundabout way I'm asking you to make the source code available. And to specify the licence you're using.
Thanks in advance.

**Comment by rimpy-custom** [comment]
I am not familiar with that stuff and do not have time to get into this, sorry. If you dislike how app disributed, do not use it. Sorry for inconvenivence.

**Comment by TBye101** [comment]
@Matyas-Cerny it looks like RimPy depending on what parts of Qt it uses might be forced into being GNU GPL. 
I'm kinda puzzled why RimPy isn't open source, but the Qt components being used are certain ones then RimPy would actually be violating Qt's license by not distributing its source code or having it publicly available.
