### ISSUE TITLE
[SYR] Trait Value bug

### ISSUE THREAD

**Issue by kamikadza13** [rimpy-custom/RimPy#46]
[Steam link](https://steamcommunity.com/sharedfiles/filedetails/?id=2451324814)

> _Load order:
> Load before ANY trait mod._

But auto sorting don't do it. Please fix

**Comment by rimpy-custom** [comment]
Not smth I am willing to fix. Check this:
https://github.com/rimpy-custom/RimPy/wiki/Autosorting
https://github.com/rimpy-custom/RimPy/wiki/How-To-Create-Load-Order-Rules-(read-this-before-any-rules-creation!)
add custom rules and share them with community.
