### ISSUE TITLE
Steam Workshop is missing [Linux]

### ISSUE THREAD

**Issue by michaloM13** [rimpy-custom/RimPy#47]
I accidentally opened RimPy.sh file and now Steam Workshop page is missing. I tried to reinstalling everything but it is still blank. Is there any way how to fix this bug?
![image](https://user-images.githubusercontent.com/102375325/160154998-3b4665ed-d684-4a70-ab18-d83bc72d8f07.png)

**Comment by rimpy-custom** [comment]
QtWebEngine fails, probably... Make sure you have Internet connection.

**Comment by michaloM13** [comment]
I have internet connection but it doesn't work. RimPy.sh had to change something in files because even when I open Windows version of RimPy with Wine it doesn't work.

**Comment by rimpy-custom** [comment]
RimPy.sh is a shell script, you may check what it did with any text editor.

**Comment by reddragonmps** [comment]
Today I was having the same issue, but I cannot confirm it was RimPy.sh fault. Running RimPy with --no-sandbox argument solved it. Seems to be a problem with loading qt local resources. I asume you can also temporarily fix it by running it with `./RimPy --no-sandbox` @michaloM13 .

**Comment by reddragonmps** [comment]
![image](https://user-images.githubusercontent.com/53922900/164789126-707bc87a-8b9d-431a-a2ea-86e0d38a3564.png)
This is what I get when i run it with my own user. no qt errors but yet no browser.
![image](https://user-images.githubusercontent.com/53922900/164789346-7e641dd8-8711-4381-a081-be27dfd5d9ac.png)
If I run it with --no-sandbox argument the app runs perfectly. (sudo and user)
Hope this helps troubleshooting.

**Comment by rimpy-custom** [comment]
Closing for now. Feel free to reopn if you still get issues.
