### ISSUE TITLE
Rimpy mod updater stop working

### ISSUE THREAD

**Issue by Lucas559-noob** [rimpy-custom/RimPy#50]
Pretty sure is because of my limited laptop, but most of times with a lot of mods, it takes ages or just stop working
[rimpy.log](https://github.com/rimpy-custom/RimPy/files/8502973/rimpy.log)
looks like is not very useful, did not saw errors on log

**Comment by rimpy-custom** [comment]
Wdym "stop working"? Did it crash?

**Comment by Lucas559-noob** [comment]
well, it just stops, maybe because it doesn't like when I alt tab to another program, it works fine if I keep the program open in screen

**Comment by rimpy-custom** [comment]
Closing for now. Feel free to reopn if you still get issues.
