### ISSUE TITLE
It opens up to a white screen.

### ISSUE THREAD

**Issue by TheReallyP** [rimpy-custom/RimPy#56]
I tried installing this as the guides show, but the four times I tried installing or reinstalling it, it opens up to a mostly blank screen. I can select things I can't see, and do stuff with them, but I don't know what to do. I looked in this mod's issues and saw something similar, but mine opens to a usable blank screen where I can select and hover over things to see words in blue boxes like names of a mod. I never used the RimPy app before, but the guy on that issue thing reported a log and picture, so here is those too. https://gist.github.com/TheReallyP/94da603ba648a3dd793378021f709fd5
![image](https://user-images.githubusercontent.com/99220890/164860573-0a400f71-7e5b-4554-aece-11df9a0827b9.png)

**Comment by rimpy-custom** [comment]
Did you try FAQ advice about white screen?

**Comment by TheReallyP** [comment]
No, where would that be?

**Comment by TheReallyP** [comment]
I found it in the wiki page, and now, it works correctly with the other file installed. Thanks for taking your time to let me know about it.
