### ISSUE TITLE
Unable to override rule with the user defined one.

### ISSUE THREAD

**Issue by H4M5TER** [rimpy-custom/RimPy#57]
There are conflicts between rules and I hope to override them.
![image](https://user-images.githubusercontent.com/21092951/167707501-e66615c1-71fa-4169-a113-02185b6a465c.png)
![image](https://user-images.githubusercontent.com/21092951/167707545-36e404e1-a33e-4501-a0a9-997ca0201a30.png)
As it, the community rules conficlted and I'm trying to believe the modder provided one.
But the conflict remains when I sort.
![image](https://user-images.githubusercontent.com/21092951/167707974-cdb3a22a-f48f-4a14-be1a-027d40855fe2.png)

**Comment by rimpy-custom** [comment]
Yous should not fix that, but report bad rule in Discord. I have manually fixed that, subscribe to RimPy Database on Steam to get updates rules pack. Feel free to reopen issue if not fixed.
