### ISSUE TITLE
[Suggestion] Add Select All button to the Convert Mod Dialog interface

### ISSUE THREAD

**Issue by mario31274** [rimpy-custom/RimPy#62]
The Downloader feature is really useful for me to check updates for local Steam workshop mods, except I have to convert them one by one in the Convert Mod dialog. It would help me a lot if there were a 'Select all' button when there were hundreds of mods to convert.

My friends and I use RimPy to share our mods with each other, but somehow we can't load the mods just by unzipping the mod pack to the Mods folder. Rimworld doesn't recognize the mods inside the self-created mod pack, and we had to put all mods inside the mod pack directly under the Mods directory for the game to load. This is where the Downloader of RimPy becomes useful, and I'm too lazy to go through the mod list to subscribe to all 200+ mods one by one.

**Comment by rimpy-custom** [comment]
That is intentional. That is important ot check each mod name <-> steam id (mod folder) for RimPy to work properly.
