### ISSUE TITLE
[suggestion] Pass command line arguments to Rimworld

### ISSUE THREAD

**Issue by Drexl** [rimpy-custom/RimPy#67]
I'd like the ability to pass command line arguments like -popupwindow to Rimworld when pressing play.

**Comment by thakyZ** [comment]
Yea, I would really like to pass that specific one to it, but to allow the ability for more if needed would be nice. I would make a pull request with the code to do this, but it sadly looks like the source isn't available.

**Comment by Drexl** [comment]
Apparently this exists if you right-click on the run button. There is even a tooltip for it. I've never seen an implementation like this. I scoured every other part of the program trying to find it.

**Comment by rimpy-custom** [comment]
Yes, it works as is. RMB on Run button to change it. Closing for now.
