### ISSUE TITLE
RimPy Asks For Missing Mods That Don't Exist Anymore, Then Doesn't Load.

### ISSUE THREAD

**Issue by Youngman86** [rimpy-custom/RimPy#68]
When I try to run RimPy, it tells me there are missing entries and the IDs they give don't load workshop pages anymore, are likely for old mods. Whether I tell it to try to download them or ignore them, it goes to a "Populating Mods" progress bar that only appears on screen if I hover over the window in the toolbar, not if I click on it. When left alone, the populating mods bar will eventually go away after a few minutes, but nothing replaces it, not even if I hover my mouse over the icon on the toolbar.

**Comment by rimpy-custom** [comment]
Press Save button and restart RimPy. Reopen issue if not fixed.

**Comment by Youngman86** [comment]
There's not a save button. There's not a window. Like I said, the populating mods bar goes away and is replaced with nothing. It doesn't bring up a window if I click on the RimPy icon in the Taskbar where it indicates the program is running, not even if I hover over it like I was doing to get the populating mods bar to show.
