### ISSUE TITLE
Dragging Mods = Crash and Issue Occured.

### ISSUE THREAD

**Issue by 1337Proxy1337** [rimpy-custom/RimPy#69]
RimPY worked fine and i had no issues whatsoever till yesterday i formatted my pc. Now it says an issue occured whenever i try to download a mod and dragging mods from inactive to active results in an instant crash. Reinstalled it and it still isn't fixed.

**Comment by 1337Proxy1337** [comment]
CMD Log before Issue Occured.
Redirecting stderr to 'C:\Users\Emil\OneDrive\Desktop\SteamCMD\logs\stderr.txt'
ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
[  0%] Checking for available update...
[----] Downloading update (0 of 63,780 KB)...
[  0%] Downloading update (2,677 of 63,780 KB)...
[  4%] Downloading update (3,770 of 63,780 KB)...
[  5%] Downloading update (4,736 of 63,780 KB)...
[  7%] Downloading update (4,948 of 63,780 KB)...
[  7%] Downloading update (6,352 of 63,780 KB)...
[  9%] Downloading update (7,030 of 63,780 KB)...
[ 11%] Downloading update (8,507 of 63,780 KB)...
[ 13%] Downloading update (9,433 of 63,780 KB)...
[ 14%] Downloading update (10,392 of 63,780 KB)...
[ 16%] Downloading update (11,317 of 63,780 KB)...
[ 17%] Downloading update (12,226 of 63,780 KB)...
[ 19%] Downloading update (13,129 of 63,780 KB)...
[ 20%] Downloading update (14,005 of 63,780 KB)...
[ 21%] Downloading update (14,930 of 63,780 KB)...
[ 23%] Downloading update (15,835 of 63,780 KB)...
[ 24%] Downloading update (16,802 of 63,780 KB)...
[ 26%] Downloading update (17,709 of 63,780 KB)...
[ 27%] Downloading update (18,622 of 63,780 KB)...
[ 29%] Downloading update (19,519 of 63,780 KB)...
[ 30%] Downloading update (20,428 of 63,780 KB)...
[ 32%] Downloading update (21,322 of 63,780 KB)...
[ 33%] Downloading update (22,221 of 63,780 KB)...
[ 34%] Downloading update (23,205 of 63,780 KB)...
[ 36%] Downloading update (24,131 of 63,780 KB)...
[ 37%] Downloading update (25,007 of 63,780 KB)...
[ 39%] Downloading update (25,917 of 63,780 KB)...
[ 40%] Downloading update (26,812 of 63,780 KB)...
[ 42%] Downloading update (27,727 of 63,780 KB)...
[ 43%] Downloading update (28,637 of 63,780 KB)...
[ 44%] Downloading update (29,613 of 63,780 KB)...
[ 46%] Downloading update (30,503 of 63,780 KB)...
[ 47%] Downloading update (31,425 of 63,780 KB)...
[ 49%] Downloading update (32,310 of 63,780 KB)...
[ 50%] Downloading update (33,221 of 63,780 KB)...
[ 52%] Downloading update (34,139 of 63,780 KB)...
[ 53%] Downloading update (34,994 of 63,780 KB)...
[ 54%] Downloading update (36,033 of 63,780 KB)...
[ 56%] Downloading update (36,923 of 63,780 KB)...
[ 57%] Downloading update (37,870 of 63,780 KB)...
[ 59%] Downloading update (38,275 of 63,780 KB)...
[ 60%] Downloading update (39,319 of 63,780 KB)...
[ 61%] Downloading update (40,327 of 63,780 KB)...
[ 63%] Downloading update (41,337 of 63,780 KB)...
[ 64%] Downloading update (42,345 of 63,780 KB)...
[ 66%] Downloading update (43,168 of 63,780 KB)...
[ 67%] Downloading update (43,849 of 63,780 KB)...
[ 68%] Downloading update (45,444 of 63,780 KB)...
[ 71%] Downloading update (45,962 of 63,780 KB)...
[ 72%] Downloading update (46,628 of 63,780 KB)...
[ 73%] Downloading update (47,571 of 63,780 KB)...
[ 74%] Downloading update (48,387 of 63,780 KB)...
[ 75%] Downloading update (49,289 of 63,780 KB)...
[ 77%] Downloading update (50,298 of 63,780 KB)...
[ 78%] Downloading update (51,193 of 63,780 KB)...
[ 80%] Downloading update (52,007 of 63,780 KB)...
[ 81%] Downloading update (53,171 of 63,780 KB)...
[ 83%] Downloading update (54,178 of 63,780 KB)...
[ 84%] Downloading update (55,061 of 63,780 KB)...
[ 86%] Downloading update (56,123 of 63,780 KB)...
[ 87%] Downloading update (57,168 of 63,780 KB)...
[ 89%] Downloading update (57,386 of 63,780 KB)...
[ 89%] Downloading update (58,537 of 63,780 KB)...
[ 91%] Downloading update (59,555 of 63,780 KB)...
[ 93%] Downloading update (60,640 of 63,780 KB)...
[ 95%] Downloading update (61,686 of 63,780 KB)...
[ 96%] Downloading update (62,870 of 63,780 KB)...
[ 98%] Downloading update (63,758 of 63,780 KB)...
[ 99%] Downloading update (63,780 of 63,780 KB)...
[100%] Download Complete.
[----] Applying update...
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Installing update...
[----] Installing update...
[----] Failed to apply update, reverting...
[----] Verifying installation...
[  0%] Downloading Update...
[  0%] Checking for available update...

**Comment by rimpy-custom** [comment]
Delete RimPy folder and RimPy config folder. then install dev build of RimPy cleanly. Closing for now, reopen if needed,
