### ISSUE TITLE
Can we have an updated Linux version and/or make the source available?

### ISSUE THREAD

**Issue by EnderShadow** [rimpy-custom/RimPy#70]
Making the source available would allow us to compile it ourselves as well as allow others to help with development.

**Comment by NightHammer1000** [comment]
Yeah. Where is the Linux Version?
Especially now with the Steam Deck its needed even more.

**Comment by ghost** [comment]
Agreed.

**Comment by reddragonmps** [comment]
I recently had to move to [Rimworld Mod Manager](https://github.com/Spoons/rmm) after I reinstalled. I couldn't make Rimpy to work again and I didn't want to bother the developer. I still prefer Rimpy over rmm, but if it ain't working there is no choice. Please bring back rimpy to Linux :penguin: :C.

**Comment by pinbuck** [comment]
Please make the source code available and source build instructions

**Comment by rimpy-custom** [comment]
Linux build was updated and added to 1.2.6.25 release. It was build on different OS (Fedora) and has some fixes for linux, hope that should work on any distro. Keep in mind that it is dev build. Do not use mods stripping and double check if delete smth. You may give feedback in our Discord.

**Comment by pinbuck** [comment]
Thank you for updating the linux build.

**Comment by Aliervo** [comment]
Thanks for the update. You might consider throwing together a docker container for us penguins, it could make it a little easier for you and us to keep in sync. I'd be happy to help you set it up if you're interested.
