### ISSUE TITLE
Crashes when checking for mod updates (invalid literal for int with base 10)

### ISSUE THREAD

**Issue by sofielean** [rimpy-custom/RimPy#71]
Hello everyone, I found a (very) minor issue with RimPy:

RimPy crashes when selecting all or any single mod and clicking on "Check for updates" in the Mods updater because RimPy tries to convert the string (folder name from mod) into a number. Changing the folder name to the corresponding mod ID made it not crash anymore.
I do not know much about python since I haven't used it in a while but even if I am the only one who noticed this maybe it would be better practice to test if the folder name is an integer before doing anything with it and notifying the user if it is not an integer.

the log file is here: [paste](https://pastebin.com/ai11qCye)

This is the first time I committed an issue, so I hope everything is correct.

**Comment by rimpy-custom** [comment]
That is intentional. Do not rename folder to smth different. It hsould be steam mod id, not smth else to work properly.
