### ISSUE TITLE
Can't setup SteamCMD

### ISSUE THREAD

**Issue by DarkShadow44** [rimpy-custom/RimPy#74]
When I try to setup SteamCMD, I get the message "An issue occured, SteamCMD was not downloaded and installed. Check your Internet connection or try to install it manually.".
I'm on Linux.

**Comment by rimpy-custom** [comment]
Related to #72

**Comment by NiekStevenss** [comment]
#98 ? had the same issue, when i put it in a "valid" location it just crashed
