### ISSUE TITLE
Checking for updates fails

### ISSUE THREAD

**Issue by DarkShadow44** [rimpy-custom/RimPy#75]
I'm on Linux. When I click "Updates" and then "Check for updates" I get the message `Ошибка открытия URL: https://api.github.com/repos/rimpy-custom/RimPy/releases`

**Comment by rimpy-custom** [comment]
There are so many Linuxes. What is your distro and version?

**Comment by rimpy-custom** [comment]
Related to #72

**Comment by DarkShadow44** [comment]
I'm on Arch Linux, up to date.
