### ISSUE TITLE
[MOD] Rimatomics & Corner Bits's texture lost some background after transformed to dds

### ISSUE THREAD

**Issue by jessefjxm** [rimpy-custom/RimPy#8]
Rimpy version: 1.1.3.18
Game version: 1.3.3117 rev669

Related mods:
Rimatomics: https://steamcommunity.com/sharedfiles/filedetails/?id=1127530465
Corner Bits: https://steamcommunity.com/sharedfiles/filedetails/?id=2578661551 

What happened:
After these 2 mod's textures transformed to dds, following building's background will turns into black:
[Rimatomics] Thor Turbine
[Rimatomics] Cooling Tower
[Corner Bits] all corners

Clear dds files can solve this problem. (background become transparent)

**Comment by rimpy-custom** [comment]
Fixed in latest stable
