### ISSUE TITLE
Unable to add mod until mod page is fully loaded in downloader tab

### ISSUE THREAD

**Issue by strdsk** [rimpy-custom/RimPy#83]
When opening a mod page that contains many gif or any big asset, it will prevent the mod to be added until all those assets are fully loaded.

Shouldn't it be available when the initial load of the DOM is complete?

**Comment by rimpy-custom** [comment]
It waits till page fully loaded, to make sure that qwebchannel javascript part be applied. There may be better way, probably. But currently it waits till page fully loaded.

**Comment by strdsk** [comment]
If all you need is to make sure DOM mutation to be applied, then you can use `MutationObserver` instead. You just have to make sure that the initial DOM is loaded then apply the observer into the parent element and track it's childlist and/or subtree.

Just a suggestion.

**Comment by rimpy-custom** [comment]
It is all about connection between widgets in Qt. According to Qt: https://doc.qt.io/qt-6/qtwebengine-overview.html#script-injection

`The DOM of a page is constructed when the document is ready, typically when the page is completely loaded. Therefore, executing scripts as soon as a document is created is not suitable for DOM operations, where one has to wait until the DOM is ready.`

**Comment by rimpy-custom** [comment]
Closing for now
