### ISSUE TITLE
Continuous crashing on launch

### ISSUE THREAD

**Issue by missargentina** [rimpy-custom/RimPy#85]
Running the latest version of Rimpy on Ubuntu 22.04. After trying to set the file path for Steam mods, Rimpy crashed and continues crashing every time I try to open it. I've attached the Rimpy log and terminal output.

When I brought this up on the Discord someone suggested increasing the inotify limit, but it's already set at 65536 which to my (limited) understanding is a lot more than needed anyway.

[rimpy_crashlog 21_08_2022 11_25_48.log](https://github.com/rimpy-custom/RimPy/files/9389441/rimpy_crashlog.21_08_2022.11_25_48.log)
[rimpy terminal log.txt](https://github.com/rimpy-custom/RimPy/files/9389442/rimpy.terminal.log.txt)

**Comment by rimpy-custom** [comment]
Closing for now. Reopen if issue wasn't fixed with latest Linux build 1.2.6.28.
