### ISSUE TITLE
Unable to use texture conversion

### ISSUE THREAD

**Issue by AldebaraanMKII** [rimpy-custom/RimPy#94]
Whenever i try to use it i get this error: https://imgur.com/D5pnhVh
W10 LTSC 2021
24gb DDR4 2133mhz
xeon 2670v3
512gb sata ssd

**Comment by rimpy-custom** [comment]
Probably smth with your OS or hardware. Should work fine on W10. What converter do you use and wahts is your GPU?

**Comment by rimpy-custom** [comment]
Closing since no answer
