### ISSUE TITLE
Rimpy listing incorrect dependencies

### ISSUE THREAD

**Issue by GameBurrow** [rimpy-custom/RimPy#97]
I have 3 mods, all that have listed only Biotech as dependencies in steam workshop page and in-game mod manager say the same, but RimPy says they require ideology also: 
![image](https://user-images.githubusercontent.com/4341091/197462625-84eda7b8-1370-4c2d-b36c-9bdf9ec463f0.png)

**Comment by rimpy-custom** [comment]
Mod pages had information about mentioned dependencies when RimPy database was built, I guess. Since you did not provide links to mod pages, I am unable to check that.

**Comment by GameBurrow** [comment]
Mods listed:
- https://steamcommunity.com/sharedfiles/filedetails/?id=2877887281
- https://steamcommunity.com/sharedfiles/filedetails/?id=2878238545
- https://steamcommunity.com/sharedfiles/filedetails/?id=2878104853

**Comment by rimpy-custom** [comment]
You were right, issue was on my side. Will be fixed in next release. Thank you for heads up.

**Comment by rimpy-custom** [comment]
should be fixed now
