### ISSUE TITLE
Wrong Path

### ISSUE THREAD

**Issue by NiekStevenss** [rimpy-custom/RimPy#98]
Rimpy cannot find the config folder... no shit
the path must contain english characters only but its stored in:
   C:\Users\Sanne Doezé\AppData\LocalLow\Ludeon Studios\RimWorld by Ludeon Studios\Config
   
logical, but rimpy says
   C:\Users\Sanne DoezÃ©\AppData\LocalLow\Ludeon Studios\RimWorld by Ludeon Studios\Config
   
now i cant use my favorite mod launcher... 0/10

**Comment by NiekStevenss** [comment]
please help rimworld with no mods is painful

**Comment by rimpy-custom** [comment]
Upload rimpy.s config.ini

**Comment by rimpy-custom** [comment]
should be fixed now
