### ISSUE TITLE
ImportError undefined symbol _ZdaPvm, version Qt_5 on Linux

### ISSUE THREAD

**Issue by TBleader** [rimpy-custom/RimPy#99]
Hello, I tried updating to the latest released version (1.2.6.27) but I am having the following error when running the executable:

>$ ./RimPy
>Traceback (most recent call last):
 > File "/home/user/Desktop/rimpy/rimpy.py", line 24, in <module>
>ImportError: /home/user/Desktop/rimpy/PyQt5/QtCore.so: undefined symbol: _ZdaPvm, version Qt_5

Is there some new dependency that is required in this version that isn't listed? It generally seems like RimPy is including any shared libraries it requires given the amount of them already present.

system info:
OS: Arch Linux
Kernel: 5.15.75-1-lts

**Comment by rimpy-custom** [comment]
Try latest prerelease

**Comment by TBleader** [comment]
Unfortunately nothing has changed when trying the [1.2.6.28](https://github.com/rimpy-custom/RimPy/releases/tag/1.2.6.28) release. I tried removing any qt5 libraries and the qt5 folder since I do have both qt5 and pyqt5 installed as a system package in case that would work as some of the other issues have been fixed that way, but that just changed it to "cannot open shared object file: no such file or directory" which would make sense given I deleted it.

Do let me know if there is some way I can provide more data or test to help try and figure this out.

If it is any help, [1.2.4.21](https://github.com/rimpy-custom/RimPy/releases/tag/1.2.4.21) (the last stable release listed for linux) works fine aside from the sorting with biotech issue that was recently fixed. So something between this version and the newer ones has changed with qt5 / pyqt5 to trigger this I guess? It seems like whatever compiled python environment just cannot find whatever _ZdaPvm is, but it's weird that this is only happening on some platforms since I've been the only one to report it.
Hopefully it isn't one of those classic "this only impacts me and literally no one else" errors.. I really hate those.

**Comment by ghost** [comment]
> Unfortunately nothing has changed when trying the [1.2.6.28](https://github.com/rimpy-custom/RimPy/releases/tag/1.2.6.28) release. I tried removing any qt5 libraries and the qt5 folder since I do have both qt5 and pyqt5 installed as a system package in case that would work as some of the other issues have been fixed that way, but that just changed it to "cannot open shared object file: no such file or directory" which would make sense given I deleted it.
> 
> Do let me know if there is some way I can provide more data or test to help try and figure this out.
> 
> If it is any help, [1.2.4.21](https://github.com/rimpy-custom/RimPy/releases/tag/1.2.4.21) (the last stable release listed for linux) works fine aside from the sorting with biotech issue that was recently fixed. So something between this version and the newer ones has changed with qt5 / pyqt5 to trigger this I guess? It seems like whatever compiled python environment just cannot find whatever _ZdaPvm is, but it's weird that this is only happening on some platforms since I've been the only one to report it. Hopefully it isn't one of those classic "this only impacts me and literally no one else" errors.. I really hate those.

I had the same error but it fixed itself out of nowhere so i don't know what to tell you, instead I'm having issues with  steamcmd not installing properly and being unable to download mods from the workshop, if it helps i tried the 1.2.4.21 release then reinstalled 1.2.6.28 and it worked this time.

**Comment by rimpy-custom** [comment]
Closing for now. Reopen if issue wasn't fixed with latest Linux build 1.2.6.28.

**Comment by TBleader** [comment]
Sadly I'm still experiencing the issue on 1.2.6.29, and as mentioned above also on 1.2.6.28

No idea what turco-ai did, since no matter how many times I download and try either version it never magically resolves itself...

I've got Qt5 and python-pyqt5 (and python-pyqt6 lol) installed, so even if it relied on local libs (i'm not convinced it does?) that should be fine. Any way I can help get a more clear picture on what is wrong to better help figure this out? Until then I've been having to use the older version that doesn't sort properly to still be able to use some functionality.
